name: CI

on:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:


        node-version: '16' 
    - name: Set up Environment Variables
      run: |
        echo "::set-env name=DB_HOST::${{ secrets.DB_HOST }}"
        echo "::set-env name=DB_USER::${{ secrets.DB_USER }}"
        echo "::set-env name=DB_PASSWORD::${{ secrets.DB_PASSWORD }}"
        echo "::set-env name=DB_NAME::${{ secrets.DB_NAME }}"
        echo "::set-env name=DB_DIALECT::${{ secrets.DB_DIALECT }}"
      shell: bash

    - name: Set up MySQL
      run: |

        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ secrets.DB_NAME }};' -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }}
        

    - name: Install project dependencies
      run: npm install

    - name: Run integration tests
      id: test
      run: |
        npm test
        echo "Test exit code: $?"
      #continue-on-error: true

    - name: On Success
      if: steps.test.outcome == 'success'
      uses: myrotvorets/set-commit-status-action@master
      with:
        sha: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: success
        context: CI/Tests
        description: 'Integration tests passed'

    - name: on failure
      if: steps.test.outcome == 'failure'
      uses: myrotvorets/set-commit-status-action@master
      with:
        sha: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        status: failure
        context: CI/Tests
        description: 'Integration tests failed'
